namespace Stash.Stdlib.Generators;

using System.Collections.Generic;
using System.Linq;
using System.Text;

internal static class CodeEmitter
{
    public static string EmitNamespace(NamespaceModel ns)
    {
        var sb = new StringBuilder();
        sb.AppendLine("// <auto-generated/>");
        sb.AppendLine("#nullable enable");
        sb.Append("namespace ").Append(ns.ContainingNamespace).AppendLine(";");
        sb.AppendLine();
        sb.AppendLine("using System;");
        sb.AppendLine("using System.Collections.Generic;");
        sb.AppendLine("using global::Stash.Runtime;");
        sb.AppendLine("using global::Stash.Stdlib;");
        sb.AppendLine("using global::Stash.Stdlib.Models;");
        sb.AppendLine("using global::Stash.Stdlib.Registration;");
        sb.AppendLine();
        sb.Append("partial class ").Append(ns.ClassName).AppendLine();
        sb.AppendLine("{");
        sb.AppendLine("    public static global::Stash.Stdlib.Registration.NamespaceDefinition Define(global::Stash.Runtime.StashCapabilities __caps = global::Stash.Runtime.StashCapabilities.All)");
        sb.AppendLine("    {");
        sb.Append("        var ns = new global::Stash.Stdlib.Registration.NamespaceBuilder(\"").Append(ns.StashName).AppendLine("\");");
        sb.Append("        ns.RequiresCapability(").Append(ns.CapabilityFullName).AppendLine(");");

        foreach (var c in ns.Constants)
        {
            EmitConstant(sb, ns, c);
        }
        foreach (var s in ns.Structs)
        {
            EmitStruct(sb, s);
        }
        foreach (var e in ns.Enums)
        {
            EmitEnum(sb, e);
        }
        foreach (var fn in ns.Functions)
        {
            EmitFunction(sb, ns, fn);
        }

        sb.AppendLine("        return ns.Build();");
        sb.AppendLine("    }");
        sb.AppendLine("}");
        return sb.ToString();
    }

    private static void EmitConstant(StringBuilder sb, NamespaceModel ns, ConstantModel c)
    {
        string deprec = c.DeprecationReplacement is null
            ? "null"
            : $"new global::Stash.Stdlib.Models.DeprecationInfo({Quote(c.DeprecationReplacement)})";
        string doc = c.Documentation is null ? "null" : Quote(c.Documentation);
        // Box value via cast to object — accessing the field by name on the partial class.
        sb.Append("        ns.Constant(")
          .Append(Quote(c.StashName)).Append(", (object)")
          .Append(c.FieldName).Append(", ")
          .Append(Quote(c.StashTypeLabel)).Append(", ")
          .Append(Quote(c.DisplayValue)).Append(", ")
          .Append(doc).Append(", ")
          .Append(deprec).AppendLine(");");
    }

    private static void EmitStruct(StringBuilder sb, StructModel s)
    {
        string doc = s.Documentation is null ? "null" : Quote(s.Documentation);
        sb.Append("        ns.Struct(").Append(Quote(s.StashName)).Append(", new global::Stash.Stdlib.Models.BuiltInField[] { ");
        for (int i = 0; i < s.Fields.Count; i++)
        {
            var f = s.Fields[i];
            if (i > 0) sb.Append(", ");
            sb.Append("new global::Stash.Stdlib.Models.BuiltInField(").Append(Quote(f.StashName)).Append(", ").Append(Quote(f.StashTypeLabel)).Append(")");
        }
        sb.Append(" }, ").Append(doc).AppendLine(");");
    }

    private static void EmitEnum(StringBuilder sb, EnumModel e)
    {
        string doc = e.Documentation is null ? "null" : Quote(e.Documentation);
        sb.Append("        ns.Enum(").Append(Quote(e.StashName)).Append(", new string[] { ");
        for (int i = 0; i < e.Members.Count; i++)
        {
            if (i > 0) sb.Append(", ");
            sb.Append(Quote(e.Members[i]));
        }
        sb.Append(" }, ").Append(doc).AppendLine(");");
    }

    private static void EmitFunction(StringBuilder sb, NamespaceModel ns, FunctionModel fn)
    {
        string qualifiedName = string.IsNullOrEmpty(ns.StashName)
            ? fn.StashName
            : ns.StashName + "." + fn.StashName;

        // Build BuiltInParam[]
        var paramExprs = new List<string>();
        foreach (var p in fn.Parameters)
        {
            paramExprs.Add($"new global::Stash.Stdlib.Models.BuiltInParam({Quote(p.StashName)}, {Quote(p.StashTypeLabel)})");
        }
        string paramArray = paramExprs.Count == 0
            ? "global::System.Array.Empty<global::Stash.Stdlib.Models.BuiltInParam>()"
            : "new global::Stash.Stdlib.Models.BuiltInParam[] { " + string.Join(", ", paramExprs) + " }";

        string variadicArg = fn.IsVariadic ? "true" : "false";
        string returnTypeArg = fn.ReturnTypeStash is null ? "null" : Quote(fn.ReturnTypeStash);
        string docArg = fn.Documentation is null ? "null" : Quote(fn.Documentation);
        string deprecArg = fn.DeprecationReplacement is null
            ? "null"
            : $"new global::Stash.Stdlib.Models.DeprecationInfo({Quote(fn.DeprecationReplacement)})";

        bool hasFnCap = fn.CapabilityFullName != "global::Stash.Runtime.StashCapabilities.None";
        if (hasFnCap)
        {
            sb.Append("        if ((__caps & ").Append(fn.CapabilityFullName).Append(") == ").Append(fn.CapabilityFullName).AppendLine(")");
            sb.AppendLine("        {");
        }
        sb.Append("        ns.Function(").Append(Quote(fn.StashName)).Append(", ").Append(paramArray).AppendLine(",");

        // Body
        if (fn.Raw)
        {
            sb.Append("            ").Append(fn.MethodName).AppendLine(",");
        }
        else
        {
            sb.AppendLine("            static (global::Stash.Runtime.IInterpreterContext ctx, global::System.ReadOnlySpan<global::Stash.Runtime.StashValue> args) =>");
            sb.AppendLine("            {");
            EmitMarshalBody(sb, ns, fn, qualifiedName);
            sb.AppendLine("            },");
        }

        sb.Append("            returnType: ").Append(returnTypeArg).AppendLine(",");
        sb.Append("            isVariadic: ").Append(variadicArg).AppendLine(",");
        sb.Append("            documentation: ").Append(docArg).AppendLine(",");
        sb.Append("            deprecation: ").Append(deprecArg).AppendLine(");");
        if (hasFnCap)
        {
            sb.AppendLine("        }");
        }
    }

    private static void EmitMarshalBody(StringBuilder sb, NamespaceModel ns, FunctionModel fn, string qualifiedName)
    {
        // Emit local extraction for each user parameter
        var callArgs = new List<string>();
        if (fn.TakesContext) callArgs.Add("ctx");

        // Each parameter gets a local
        int stashIndex = 0;
        for (int i = 0; i < fn.Parameters.Count; i++)
        {
            var p = fn.Parameters[i];
            string local = "p" + i;
            if (p.IsParamsArray)
            {
                // Variadic: collect remaining
                sb.Append("                global::Stash.Runtime.StashValue[] ").Append(local).Append(" = args.Length > ").Append(stashIndex)
                    .Append(" ? args.Slice(").Append(stashIndex).Append(").ToArray() : global::System.Array.Empty<global::Stash.Runtime.StashValue>();").AppendLine();
                callArgs.Add(local);
                continue;
            }

            string extractor = p.ExtractorExpression
                .Replace("{ARGS}", "args")
                .Replace("{INDEX}", stashIndex.ToString())
                .Replace("{FUNC}", qualifiedName);

            string typeDecl = ResolveCSharpTypeForLocal(p);

            if (p.HasDefaultValue)
            {
                if (p.IsNullable)
                {
                    // Nullable: missing OR Stash null → C# default
                    sb.Append("                ").Append(typeDecl).Append(" ").Append(local).Append(";").AppendLine();
                    sb.Append("                if (args.Length <= ").Append(stashIndex).Append(" || args[").Append(stashIndex).Append("].IsNull) ")
                      .Append(local).Append(" = ").Append(p.DefaultValueLiteral ?? "null").Append(";").AppendLine();
                    sb.Append("                else ").Append(local).Append(" = ").Append(extractor).Append(";").AppendLine();
                }
                else
                {
                    // Non-nullable: missing → default; explicit Stash null → TypeError (extractor throws naturally)
                    sb.Append("                ").Append(typeDecl).Append(" ").Append(local).Append(" = args.Length > ").Append(stashIndex)
                      .Append(" ? ").Append(extractor).Append(" : ").Append(p.DefaultValueLiteral ?? "default").Append(";").AppendLine();
                }
            }
            else
            {
                sb.Append("                ").Append(typeDecl).Append(" ").Append(local).Append(" = ").Append(extractor).Append(";").AppendLine();
            }

            callArgs.Add(local);
            stashIndex++;
        }

        // Invoke
        string invocation = fn.MethodName + "(" + string.Join(", ", callArgs) + ")";

        // Wrap return
        if (fn.ReturnTypeFullName == "void")
        {
            sb.Append("                ").Append(invocation).AppendLine(";");
            sb.AppendLine("                return global::Stash.Runtime.StashValue.Null;");
        }
        else if (fn.ReturnTypeFullName == "passthrough")
        {
            sb.Append("                return ").Append(invocation).AppendLine(";");
        }
        else
        {
            // ReturnTypeFullName is the wrapped expression template with {BODY}
            string wrap = fn.ReturnTypeFullName.Replace("{BODY}", invocation);
            sb.Append("                return ").Append(wrap).AppendLine(";");
        }
    }

    private static string ResolveCSharpTypeForLocal(ParameterModel p)
    {
        // If the underlying C# type is StashValue, always declare the local as StashValue —
        // this covers the passthrough case where a [StashParam(Type="number")] is applied to a
        // StashValue parameter so the body can preserve int-ness.
        if (p.CSharpTypeFullName == "Stash.Runtime.StashValue")
            return "global::Stash.Runtime.StashValue";

        // Prefer the C# type that matches the extractor return for ergonomic body invocation.
        switch (p.StashTypeLabel)
        {
            case "int": return "long";
            case "float": return "double";
            case "number": return "double";
            case "string": return p.IsNullable ? "string?" : "string";
            case "bool": return "bool";
            case "byte": return "byte";
            case "buffer": return "byte[]";
            case "array": return "global::System.Collections.Generic.List<global::Stash.Runtime.StashValue>";
            case "dict": return "global::Stash.Runtime.Types.StashDictionary";
            case "any": return "global::Stash.Runtime.StashValue";
            case "function": return "global::Stash.Runtime.IStashCallable";
        }
        return "global::Stash.Runtime.StashValue";
    }

    public static string EmitRegistry(string assemblyName, IReadOnlyList<NamespaceModel> namespaces)
    {
        var sb = new StringBuilder();
        sb.AppendLine("// <auto-generated/>");
        sb.AppendLine("#nullable enable");
        sb.AppendLine("namespace Stash.Stdlib;");
        sb.AppendLine();
        sb.AppendLine("using System;");
        sb.AppendLine("using System.Collections.Generic;");
        sb.AppendLine();
        sb.AppendLine("internal static class GeneratedStdlibRegistry");
        sb.AppendLine("{");
        sb.AppendLine("    public static global::System.Collections.Generic.IEnumerable<(global::System.Func<global::Stash.Runtime.StashCapabilities, global::Stash.Stdlib.Registration.NamespaceDefinition> Factory, global::Stash.Runtime.StashCapabilities Required)> All()");
        sb.AppendLine("    {");
        if (namespaces.Count == 0)
        {
            sb.AppendLine("        yield break;");
        }
        else
        {
            foreach (var ns in namespaces)
            {
                sb.Append("        yield return ((global::System.Func<global::Stash.Runtime.StashCapabilities, global::Stash.Stdlib.Registration.NamespaceDefinition>)(__caps => global::")
                  .Append(ns.ClassFullName).Append(".Define(__caps)), ")
                  .Append(ns.CapabilityFullName).AppendLine(");");
            }
        }
        sb.AppendLine("    }");
        sb.AppendLine("}");
        return sb.ToString();
    }

    private static string Quote(string s)
    {
        var sb = new StringBuilder(s.Length + 2);
        sb.Append('"');
        foreach (char c in s)
        {
            switch (c)
            {
                case '\\': sb.Append("\\\\"); break;
                case '"': sb.Append("\\\""); break;
                case '\n': sb.Append("\\n"); break;
                case '\r': sb.Append("\\r"); break;
                case '\t': sb.Append("\\t"); break;
                case '\0': sb.Append("\\0"); break;
                default:
                    if (c < 0x20) sb.Append("\\u").Append(((int)c).ToString("x4"));
                    else sb.Append(c);
                    break;
            }
        }
        sb.Append('"');
        return sb.ToString();
    }
}
