namespace Stash.Tests.Stdlib;

using System.IO;
using System.Reflection;
using Stash.Tests.Interpreting;
using Xunit;

/// <summary>
/// Bash-decision parity tests for <c>path.match(path, pattern) -&gt; bool</c>.
///
/// The fixture <c>path-match-bash-parity.tsv</c> (committed at
/// <c>Stash.Tests/Stdlib/Fixtures/path-match-bash-parity.tsv</c>) was
/// generated by <c>scripts/path-match/gen-bash-parity-fixture.sh</c>, which
/// evaluates every <c>(pattern, path)</c> pair under bash
/// <c>shopt -s globstar nullglob extglob</c> using
/// <c>[[ "$path" == $pattern ]]</c>.  This is the oracle.
///
/// <list type="bullet">
///   <item><description>
///     <see cref="BashParity_PathMatchReturnsOracleVerdict"/> — skipped until
///     P2 implements <c>path.match</c>.  Removing the <c>Skip</c> attribute
///     and making every row pass is the P2 acceptance criterion.
///   </description></item>
///   <item><description>
///     <see cref="PathMatchBashParityFixture_HasShapeCoverage"/> — validates
///     the fixture's structural completeness.  Must be GREEN in P1 and stay
///     green through all subsequent phases.
///   </description></item>
/// </list>
/// </summary>
public class PathMatchBashParityTests : StashTestBase
{
    // -------------------------------------------------------------------------
    // Fixture loading
    // -------------------------------------------------------------------------

    private const string ResourceName =
        "Stash.Tests.Stdlib.Fixtures.path-match-bash-parity.tsv";

    /// <summary>Loads every non-empty, non-comment row from the embedded fixture.</summary>
    private static IReadOnlyList<(string Pattern, string Path, bool Expected)> LoadFixtureRows()
    {
        Assembly asm = typeof(PathMatchBashParityTests).Assembly;
        using Stream? stream = asm.GetManifestResourceStream(ResourceName);
        if (stream is null)
            throw new FileNotFoundException(
                $"Embedded fixture '{ResourceName}' not found. " +
                $"Available: {string.Join(", ", asm.GetManifestResourceNames())}");

        using var reader = new StreamReader(stream);
        var rows = new List<(string, string, bool)>();

        string? line;
        while ((line = reader.ReadLine()) is not null)
        {
            if (string.IsNullOrWhiteSpace(line) || line.StartsWith('#'))
                continue;

            string[] parts = line.Split('\t');
            if (parts.Length != 3)
                throw new InvalidDataException(
                    $"Expected 3 tab-separated columns, got {parts.Length}: '{line}'");

            string pattern = parts[0];
            string path    = parts[1];
            bool expected  = parts[2].Trim() switch
            {
                "true"  => true,
                "false" => false,
                var v   => throw new InvalidDataException($"Unexpected bool value: '{v}'")
            };

            rows.Add((pattern, path, expected));
        }

        return rows;
    }

    // -------------------------------------------------------------------------
    // Data source for the [Theory] — evaluated at discovery time (must be
    // self-contained and not reference any P2 symbols).
    // -------------------------------------------------------------------------

    public static IEnumerable<object[]> BashParityRows()
    {
        foreach (var (pattern, path, expected) in LoadFixtureRows())
            yield return [pattern, path, expected];
    }

    // -------------------------------------------------------------------------
    // P1 skeleton: skipped until P2 implements path.match.
    //
    // The theory calls path.match through the Stash Run harness (a string
    // literal), so it compiles without PathBuiltIns.Match existing yet.
    // -------------------------------------------------------------------------

    /// <summary>
    /// For every row in the bash-oracle fixture: asserts that
    /// <c>path.match(pattern, path)</c> returns the same boolean verdict that
    /// bash <c>[[ "$path" == $pattern ]]</c> produced under globstar.
    ///
    /// <b>Skip removed in P2</b> — this is the intentional tripwire.
    /// </summary>
    [Theory(Skip = "implementation lands in P2")]
    [MemberData(nameof(BashParityRows))]
    public void BashParity_PathMatchReturnsOracleVerdict(
        string pattern, string path, bool expected)
    {
        // Escape backslashes and double-quotes for embedding in a Stash string literal.
        string escapedPattern = pattern.Replace("\\", "\\\\").Replace("\"", "\\\"");
        string escapedPath    = path.Replace("\\", "\\\\").Replace("\"", "\\\"");

        object? result = Run(
            $"""let result = path.match("{escapedPattern}", "{escapedPath}");""");

        Assert.Equal(expected, result);
    }

    // -------------------------------------------------------------------------
    // P1 shape-coverage fact — must NOT be skipped; must be green now.
    // -------------------------------------------------------------------------

    /// <summary>
    /// Verifies the committed fixture has the minimum structural coverage
    /// required by the brief:
    /// <list type="bullet">
    ///   <item><description>More than 50 rows.</description></item>
    ///   <item><description>At least one row with a <c>**</c> pattern.</description></item>
    ///   <item><description>At least one row where a lone <c>*</c> (not <c>**</c>) matches a path
    ///     that contains more <c>/</c> segments than the pattern — proving <c>*</c> crosses <c>/</c>.</description></item>
    ///   <item><description>At least one row with a <c>?</c> pattern.</description></item>
    ///   <item><description>At least one row with a character-class pattern (<c>[…]</c>).</description></item>
    ///   <item><description>At least one literal-only pattern (no metacharacters).</description></item>
    /// </list>
    /// </summary>
    [Fact]
    public void PathMatchBashParityFixture_HasShapeCoverage()
    {
        var rows = LoadFixtureRows();

        // Minimum row count.
        Assert.True(rows.Count > 50,
            $"Fixture has only {rows.Count} rows; expected > 50.");

        // ** construct: at least one row whose pattern contains "**".
        Assert.True(
            rows.Any(r => r.Pattern.Contains("**")),
            "No row with '**' in pattern.");

        // * crossing /: a lone-* pattern (no **) where expected==true and the
        // path contains more '/' separators than the pattern — i.e. the '*'
        // matched across at least one '/'.
        bool hasStarCrossingSlash = rows.Any(r =>
            r.Expected == true &&
            r.Pattern.Contains('*') &&
            !r.Pattern.Contains("**") &&
            r.Path.Count(c => c == '/') > r.Pattern.Count(c => c == '/'));

        Assert.True(hasStarCrossingSlash,
            "No row demonstrating '*' crossing '/' (a lone-* pattern expected=true " +
            "where path has more '/' than pattern).");

        // ? construct.
        Assert.True(
            rows.Any(r => r.Pattern.Contains('?')),
            "No row with '?' in pattern.");

        // Character class [.
        Assert.True(
            rows.Any(r => r.Pattern.Contains('[')),
            "No row with '[…]' character class in pattern.");

        // Literal-only: no metacharacter (* ? [ \).
        bool hasLiteral = rows.Any(r =>
            !r.Pattern.Contains('*') &&
            !r.Pattern.Contains('?') &&
            !r.Pattern.Contains('[') &&
            !r.Pattern.Contains('\\'));

        Assert.True(hasLiteral,
            "No literal-only row (pattern with no metacharacters).");
    }
}
