namespace Stash.Docs;

using System;
using System.Collections.Generic;
using System.IO;
using System.Linq;
using System.Text;
using Stash.Runtime;
using Stash.Runtime.Errors;
using Stash.Stdlib;
using Stash.Stdlib.Models;
using Stash.Stdlib.Registration;

/// <summary>
/// Deterministic Markdown generator for the standard library reference.
/// The generator reads <see cref="StdlibDefinitions"/> metadata and writes
/// canonical Markdown. Running the generator twice without metadata
/// changes produces byte-identical output, so a clean-worktree git diff
/// check is the only CI signal required.
/// </summary>
public static class ReferenceGenerator
{
    private const string DocTitle = "Stash — Standard Library Reference";

    /// <summary>The relative path the generator writes when no override is supplied.</summary>
    public const string DefaultRelativePath = "docs/Stash — Standard Library Reference.md";

    public static string Generate()
    {
        var sb = new StringBuilder();
        // Ordered, capability-All view: the user-facing reference documents
        // every namespace the runtime knows about, regardless of capability gate.
        var namespaces = StdlibDefinitions.GetNamespaces(StashCapabilities.All);
        var globalNs = namespaces.FirstOrDefault(n => n.IsGlobal);
        var nonGlobal = namespaces.Where(n => !n.IsGlobal).ToArray();

        EmitFrontMatter(sb);
        EmitTableOfContents(sb, nonGlobal);
        EmitHowToRead(sb);
        EmitGlobalSection(sb, globalNs);
        foreach (var ns in nonGlobal)
        {
            EmitNamespace(sb, ns);
        }
        EmitAppendices(sb, namespaces);

        return Normalize(sb.ToString());
    }

    public static void WriteTo(string absolutePath)
    {
        var output = Generate();
        // Force LF endings and no BOM, matching repo convention.
        File.WriteAllText(absolutePath, output, new UTF8Encoding(encoderShouldEmitUTF8Identifier: false));
    }

    // ── Top matter ───────────────────────────────────────────────────────────

    private static void EmitFrontMatter(StringBuilder sb)
    {
        sb.Append("# ").AppendLine(DocTitle);
        sb.AppendLine();
        sb.AppendLine("> Generated reference for the Stash standard library. The API inventory in this file is");
        sb.AppendLine("> produced from `StdlibDefinitions` metadata by `Stash.Docs`. Do not edit this file by hand —");
        sb.AppendLine("> run `dotnet run --project Stash.Docs/` to regenerate after changing stdlib metadata.");
        sb.AppendLine(">");
        sb.AppendLine("> **Companion documents:**");
        sb.AppendLine(">");
        sb.AppendLine("> - [Language Specification](Stash%20—%20Language%20Specification.md) — syntax, semantics, scoping, interpreter");
        sb.AppendLine("> - [TAP — Testing Infrastructure](TAP%20—%20Testing%20Infrastructure.md) — test runner, `test` / `assert`");
        sb.AppendLine("> - [Shell — Interactive Shell Mode](Shell%20—%20Interactive%20Shell%20Mode.md) — `shell`, `alias`, `prompt`, `complete`");
        sb.AppendLine("> - [TPL — Templating Engine](TPL%20—%20Templating%20Engine.md) — `tpl` deep dive");
        sb.AppendLine("> - [PKG — Package Manager CLI](PKG%20—%20Package%20Manager%20CLI.md) — `pkg`");
        sb.AppendLine("> - [Registry — Package Registry](Registry%20—%20Package%20Registry.md) — registry server");
        sb.AppendLine("> - [LSP — Language Server Protocol](LSP%20—%20Language%20Server%20Protocol.md)");
        sb.AppendLine("> - [DAP — Debug Adapter Protocol](DAP%20—%20Debug%20Adapter%20Protocol.md)");
        sb.AppendLine();
        sb.AppendLine("---");
        sb.AppendLine();
    }

    private static void EmitTableOfContents(StringBuilder sb, IReadOnlyList<NamespaceDefinition> namespaces)
    {
        sb.AppendLine("## Table of Contents");
        sb.AppendLine();
        sb.AppendLine("1. [How to Read This Reference](#how-to-read-this-reference)");
        sb.AppendLine("2. [Global Functions and Types](#global-functions-and-types)");

        int idx = 3;
        foreach (var ns in namespaces)
        {
            string heading = NamespaceHeading(ns);
            string anchor = HeadingAnchor(heading);
            sb.Append(idx++).Append(". [`").Append(ns.Name).Append("`](#").Append(anchor).AppendLine(")");
        }

        sb.Append(idx++).AppendLine(". [Appendix A — Deprecated Members](#appendix-a--deprecated-members)");
        sb.Append(idx).AppendLine(". [Appendix B — Capability-Gated Namespaces](#appendix-b--capability-gated-namespaces)");
        sb.AppendLine();
        sb.AppendLine("---");
        sb.AppendLine();
    }

    private static void EmitHowToRead(StringBuilder sb)
    {
        sb.AppendLine("## How to Read This Reference");
        sb.AppendLine();
        sb.AppendLine("Every namespace section follows the same shape: a brief purpose statement, a capability requirement,");
        sb.AppendLine("a list of types/constants the namespace registers, a function summary table, and per-function details.");
        sb.AppendLine();
        sb.AppendLine("### Signature notation");
        sb.AppendLine();
        sb.AppendLine("Function signatures use Stash-facing types — the C# implementation type is not exposed.");
        sb.AppendLine();
        sb.AppendLine("```");
        sb.AppendLine("namespace.function(required: type, optional?: type, ...rest) -> returnType");
        sb.AppendLine("```");
        sb.AppendLine();
        sb.AppendLine("- `name: type` — required parameter and its Stash type label.");
        sb.AppendLine("- `name?: type` — optional parameter; calls may omit it.");
        sb.AppendLine("- `...rest` — variadic tail; remaining arguments are bundled into an array.");
        sb.AppendLine("- `-> type` — the Stash return type. `null` means the function returns no useful value.");
        sb.AppendLine();
        sb.AppendLine("### Type labels");
        sb.AppendLine();
        sb.AppendLine("| Label                  | Meaning                                                       |");
        sb.AppendLine("| ---------------------- | ------------------------------------------------------------- |");
        sb.AppendLine("| `int`                  | 64-bit signed integer                                         |");
        sb.AppendLine("| `float`                | 64-bit IEEE-754 double                                        |");
        sb.AppendLine("| `number`               | Accepts either `int` or `float`                               |");
        sb.AppendLine("| `string`               | UTF-16 string                                                 |");
        sb.AppendLine("| `bool`                 | Boolean                                                       |");
        sb.AppendLine("| `byte`                 | Unsigned 8-bit integer (0–255)                                |");
        sb.AppendLine("| `buffer`               | Byte array                                                    |");
        sb.AppendLine("| `array`                | Heterogeneous array of `any`                                  |");
        sb.AppendLine("| `array<T>` / `T[]`     | Typed array                                                   |");
        sb.AppendLine("| `dict`                 | String-keyed dictionary                                       |");
        sb.AppendLine("| `function`             | A callable value                                              |");
        sb.AppendLine("| `Future<T>`            | Pending result returned by an `async` function or `task.run`  |");
        sb.AppendLine("| `secret`               | A `secret(...)`-wrapped value; auto-redacts on stringify      |");
        sb.AppendLine("| Named struct / enum    | A built-in struct or enum from the same namespace             |");
        sb.AppendLine("| `any`                  | Any Stash value                                               |");
        sb.AppendLine();
        sb.AppendLine("### Errors and throws");
        sb.AppendLine();
        sb.AppendLine("Built-in error types are documented in [Global Functions and Types](#global-functions-and-types).");
        sb.AppendLine("Each function lists the error types it may throw under **Throws**. Typed `catch` clauses match");
        sb.AppendLine("the listed types — see the Language Specification's error-handling section.");
        sb.AppendLine();
        sb.AppendLine("### Capability gates");
        sb.AppendLine();
        sb.AppendLine("Some namespaces require capabilities to be enabled. Embedded hosts can omit capabilities to disable");
        sb.AppendLine("the matching namespaces entirely. The capability requirement is shown at the top of each namespace");
        sb.AppendLine("section as **Capability:** `Network` / `FileSystem` / `Process` / `Environment` / `Shell` /");
        sb.AppendLine("`Scheduler`, or _none_ when the namespace is always available.");
        sb.AppendLine();
        sb.AppendLine("### Deprecation");
        sb.AppendLine();
        sb.AppendLine("Deprecated members are marked _(deprecated — use `replacement`)_ and surface through the static");
        sb.AppendLine("analysis rule `SA0830`. A consolidated list lives in [Appendix A](#appendix-a--deprecated-members).");
        sb.AppendLine();
        sb.AppendLine("---");
        sb.AppendLine();
    }

    // ── Global section ───────────────────────────────────────────────────────

    private static void EmitGlobalSection(StringBuilder sb, NamespaceDefinition? globalNs)
    {
        sb.AppendLine("## Global Functions and Types");
        sb.AppendLine();
        sb.AppendLine("Names in this section are reachable without a namespace qualifier — they live directly in the");
        sb.AppendLine("global scope.");
        sb.AppendLine();

        EmitBuiltInErrorTypes(sb);

        if (globalNs is null)
        {
            sb.AppendLine("---");
            sb.AppendLine();
            return;
        }

        var globalStructs = globalNs.Structs
            .Where(s => !IsErrorTypeStruct(s.Name))
            .OrderBy(s => s.Name, StringComparer.Ordinal)
            .ToArray();
        var globalEnums = globalNs.Enums.OrderBy(e => e.Name, StringComparer.Ordinal).ToArray();
        EmitTypesSection(sb, globalStructs, globalEnums, headingLevel: 3);

        if (globalNs.Functions.Count > 0)
        {
            sb.AppendLine("### Functions");
            sb.AppendLine();
            EmitFunctionSummaryTable(sb, globalNs.Functions, qualified: false);
            sb.AppendLine("### Function Details");
            sb.AppendLine();
            foreach (var fn in globalNs.Functions)
            {
                EmitFunctionDetail(sb, fn, qualified: false);
            }
        }

        sb.AppendLine("---");
        sb.AppendLine();
    }

    private static void EmitBuiltInErrorTypes(StringBuilder sb)
    {
        sb.AppendLine("### Built-in Error Types");
        sb.AppendLine();
        sb.AppendLine("Stash defines a set of built-in named error types. These types are globally visible — no import");
        sb.AppendLine("required. They can be thrown with struct-literal syntax and caught by typed `catch` clauses.");
        sb.AppendLine();
        sb.AppendLine("| Type | Fields | When thrown |");
        sb.AppendLine("| ---- | ------ | ----------- |");

        foreach (var m in BuiltInErrorRegistry.Metadata.Values.OrderBy(m => m.Name, StringComparer.Ordinal))
        {
            sb.Append("| `").Append(m.Name).Append("` | ").Append(FormatErrorFields(m)).Append(" | ").Append(m.Description).AppendLine(" |");
        }
        sb.AppendLine();
        sb.AppendLine("All caught errors expose `.message: string`, `.type: string`, and `.stack: array<string>` in");
        sb.AppendLine("addition to any type-specific fields shown above.");
        sb.AppendLine();
    }

    private static string FormatErrorFields(BuiltInErrorMetadata m)
    {
        // Base fields are always present; extra fields come from the attribute metadata.
        var parts = new List<string> { "`message: string`" };
        for (int i = 0; i < m.Properties.Count; i++)
        {
            string type = i < m.PropertyTypes.Count ? m.PropertyTypes[i] : "any";
            parts.Add("`" + m.Properties[i] + ": " + type + "`");
        }
        return string.Join(", ", parts);
    }

    private static bool IsErrorTypeStruct(string name) => BuiltInErrorRegistry.IsBuiltInName(name);

    // ── Namespace section ────────────────────────────────────────────────────

    private static void EmitNamespace(StringBuilder sb, NamespaceDefinition ns)
    {
        string heading = NamespaceHeading(ns);
        sb.Append("## ").AppendLine(heading);
        sb.AppendLine();
        sb.Append("**Capability:** ").AppendLine(CapabilityLabel(ns.RequiredCapability));

        var aggregatedThrows = AggregateThrows(ns);
        if (aggregatedThrows.Count > 0)
        {
            sb.Append("**Throws:** ");
            sb.AppendLine(string.Join(", ", aggregatedThrows.Select(t => "`" + t + "`")));
        }
        sb.AppendLine();

        EmitTypesSection(sb, ns.Structs, ns.Enums, headingLevel: 3);
        EmitConstantsSection(sb, ns.Constants);

        if (ns.Functions.Count > 0)
        {
            sb.AppendLine("### Functions");
            sb.AppendLine();
            EmitFunctionSummaryTable(sb, ns.Functions, qualified: true);
            sb.AppendLine("### Function Details");
            sb.AppendLine();
            foreach (var fn in ns.Functions)
            {
                EmitFunctionDetail(sb, fn, qualified: true);
            }
        }

        sb.AppendLine("---");
        sb.AppendLine();
    }

    private static string NamespaceHeading(NamespaceDefinition ns)
    {
        // The heading shape ("`name` — Human") drives both display and anchor.
        // Keep it deterministic and tied to the namespace name.
        string human = HumanizeNamespace(ns.Name);
        return $"`{ns.Name}` — {human}";
    }

    private static string HumanizeNamespace(string name)
    {
        // Look up the curated human name; fall back to the namespace identifier
        // so unknown namespaces still render predictably.
        return HumanNames.TryGetValue(name, out var human) ? human : name;
    }

    // Curated long-form titles. New namespaces fall back to the bare identifier
    // and can be added here without affecting the API surface.
    private static readonly IReadOnlyDictionary<string, string> HumanNames = new Dictionary<string, string>(StringComparer.Ordinal)
    {
        ["alias"] = "Shell Aliases",
        ["archive"] = "Archive Operations",
        ["args"] = "Argument Parsing",
        ["arr"] = "Array Operations",
        ["assert"] = "Assertions",
        ["buf"] = "Byte Buffer Operations",
        ["complete"] = "Tab Completion",
        ["config"] = "Format-Agnostic Configuration",
        ["conv"] = "Type Conversion",
        ["crypto"] = "Cryptography and Hashing",
        ["csv"] = "CSV Parsing and Writing",
        ["dict"] = "Dictionary Operations",
        ["dns"] = "DNS Resolution",
        ["encoding"] = "Encoding and Decoding",
        ["env"] = "Environment and Process State",
        ["fs"] = "File System Operations",
        ["http"] = "HTTP Client",
        ["ini"] = "INI Configuration",
        ["io"] = "Standard I/O",
        ["json"] = "JSON",
        ["log"] = "Structured Logging",
        ["math"] = "Math Functions",
        ["net"] = "Networking Utilities",
        ["path"] = "Path Manipulation",
        ["pkg"] = "Package Manager",
        ["process"] = "Process Management",
        ["prompt"] = "REPL Prompt Customisation",
        ["re"] = "Regular Expressions",
        ["scheduler"] = "OS Service Management",
        ["sftp"] = "SFTP File Transfer",
        ["shell"] = "Interactive Shell State",
        ["signal"] = "Signal Handling",
        ["ssh"] = "SSH Remote Execution",
        ["str"] = "String Operations",
        ["sys"] = "System Information",
        ["task"] = "Parallel Tasks",
        ["tcp"] = "TCP Sockets",
        ["term"] = "Terminal Formatting",
        ["test"] = "Test Framework",
        ["time"] = "Time and Date",
        ["toml"] = "TOML",
        ["tpl"] = "Templating",
        ["udp"] = "UDP Datagrams",
        ["ws"] = "WebSockets",
        ["xml"] = "XML",
        ["yaml"] = "YAML",
    };

    private static string CapabilityLabel(StashCapabilities cap)
    {
        if (cap == StashCapabilities.None) return "_none — always available_";
        return "`" + cap.ToString() + "`";
    }

    private static SortedSet<string> AggregateThrows(NamespaceDefinition ns)
    {
        var set = new SortedSet<string>(StringComparer.Ordinal);
        foreach (var fn in ns.Functions)
        {
            if (fn.Throws is null) continue;
            foreach (var t in fn.Throws)
                set.Add(t.ErrorType);
        }
        return set;
    }

    // ── Types and constants ──────────────────────────────────────────────────

    private static void EmitTypesSection(StringBuilder sb, IReadOnlyList<BuiltInStruct> structs, IReadOnlyList<BuiltInEnum> enums, int headingLevel)
    {
        if (structs.Count == 0 && enums.Count == 0) return;

        string hashes = new('#', headingLevel);
        sb.Append(hashes).AppendLine(" Types");
        sb.AppendLine();

        foreach (var s in structs)
        {
            sb.Append(hashes).Append("# `").Append(s.Name).AppendLine("` struct");
            sb.AppendLine();
            if (!string.IsNullOrEmpty(s.Description))
            {
                sb.AppendLine(s.Description);
                sb.AppendLine();
            }
            sb.AppendLine("| Field | Type |");
            sb.AppendLine("| ----- | ---- |");
            foreach (var f in s.Fields)
            {
                sb.Append("| `").Append(f.Name).Append("` | ").Append(FormatType(f.Type)).AppendLine(" |");
            }
            sb.AppendLine();
        }

        foreach (var e in enums)
        {
            sb.Append(hashes).Append("# `").Append(e.Name).AppendLine("` enum");
            sb.AppendLine();
            if (!string.IsNullOrEmpty(e.Description))
            {
                sb.AppendLine(e.Description);
                sb.AppendLine();
            }
            sb.Append("Members: ");
            sb.AppendLine(string.Join(", ", e.Members.Select(m => "`" + m + "`")));
            sb.AppendLine();
        }
    }

    private static void EmitConstantsSection(StringBuilder sb, IReadOnlyList<NamespaceConstant> constants)
    {
        if (constants.Count == 0) return;

        sb.AppendLine("### Constants");
        sb.AppendLine();
        sb.AppendLine("| Name | Type | Value | Description |");
        sb.AppendLine("| ---- | ---- | ----- | ----------- |");

        foreach (var c in constants)
        {
            var doc = DocString.Parse(c.Documentation);
            string desc = doc.SummaryFirstSentence();
            if (c.Deprecation is not null)
            {
                string suffix = $"_Deprecated — use `{c.Deprecation.ReplacementQualifiedName}`._";
                desc = string.IsNullOrEmpty(desc) ? suffix : desc + " " + suffix;
            }
            sb.Append("| `").Append(c.QualifiedName).Append("` | ")
              .Append(FormatType(c.Type)).Append(" | ")
              .Append(InlineCodeIfShort(c.Value)).Append(" | ")
              .Append(EscapeTableCell(desc)).AppendLine(" |");
        }
        sb.AppendLine();
    }

    // ── Functions ────────────────────────────────────────────────────────────

    private static void EmitFunctionSummaryTable(StringBuilder sb, IReadOnlyList<NamespaceFunction> functions, bool qualified)
    {
        sb.AppendLine("| Function | Returns | Throws | Description |");
        sb.AppendLine("| -------- | ------- | ------ | ----------- |");
        foreach (var fn in functions)
        {
            var doc = DocString.Parse(fn.Documentation);
            string desc = doc.SummaryFirstSentence();
            if (fn.Deprecation is not null)
            {
                string suffix = $"_Deprecated — use `{fn.Deprecation.ReplacementQualifiedName}`._";
                desc = string.IsNullOrEmpty(desc) ? suffix : desc + " " + suffix;
            }
            sb.Append("| ").Append(qualified ? "`" + fn.QualifiedName + "`" : "`" + fn.Name + "`")
              .Append(" | ").Append(FormatType(fn.ReturnType))
              .Append(" | ").Append(ThrowsCell(fn.Throws))
              .Append(" | ").Append(EscapeTableCell(desc)).AppendLine(" |");
        }
        sb.AppendLine();
    }

    private static void EmitFunctionDetail(StringBuilder sb, NamespaceFunction fn, bool qualified)
    {
        string display = qualified ? fn.QualifiedName : fn.Name;
        string signature = FormatSignature(display, fn);
        sb.Append("#### `").Append(signature).AppendLine("`");
        sb.AppendLine();

        if (fn.Deprecation is not null)
        {
            sb.Append("> _Deprecated — use `").Append(fn.Deprecation.ReplacementQualifiedName).AppendLine("` instead._");
            sb.AppendLine();
        }

        var doc = DocString.Parse(fn.Documentation);
        if (!string.IsNullOrEmpty(doc.Summary))
        {
            sb.AppendLine(doc.Summary);
            sb.AppendLine();
        }

        if (fn.Parameters.Length > 0)
        {
            sb.AppendLine("**Parameters:**");
            sb.AppendLine();
            foreach (var p in fn.Parameters)
            {
                sb.Append("- `").Append(p.Name).Append("`");
                if (!string.IsNullOrEmpty(p.Type))
                    sb.Append(": ").Append(FormatTypeRaw(p.Type));
                if (doc.Params.TryGetValue(p.Name, out var desc) && !string.IsNullOrEmpty(desc))
                    sb.Append(" — ").Append(desc);
                sb.AppendLine();
            }
            sb.AppendLine();
        }

        if (!string.IsNullOrEmpty(fn.ReturnType) || !string.IsNullOrEmpty(doc.Returns))
        {
            sb.Append("**Returns:** ");
            if (!string.IsNullOrEmpty(fn.ReturnType))
                sb.Append(FormatTypeRaw(fn.ReturnType!));
            if (!string.IsNullOrEmpty(doc.Returns))
            {
                if (!string.IsNullOrEmpty(fn.ReturnType)) sb.Append(" — ");
                sb.Append(doc.Returns);
            }
            sb.AppendLine();
            sb.AppendLine();
        }

        if (fn.Throws is not null && fn.Throws.Length > 0)
        {
            sb.AppendLine("**Throws:**");
            sb.AppendLine();
            foreach (var t in fn.Throws)
            {
                sb.Append("- `").Append(t.ErrorType).Append("`");
                if (!string.IsNullOrEmpty(t.Description))
                    sb.Append(" — ").Append(t.Description);
                sb.AppendLine();
            }
            sb.AppendLine();
        }
    }

    private static string FormatSignature(string displayName, NamespaceFunction fn)
    {
        var parts = new List<string>();
        for (int i = 0; i < fn.Parameters.Length; i++)
        {
            var p = fn.Parameters[i];
            bool isVariadicTail = fn.IsVariadic && i == fn.Parameters.Length - 1;
            string name = isVariadicTail ? "..." + p.Name : p.Name;
            if (!string.IsNullOrEmpty(p.Type))
                parts.Add(name + ": " + p.Type);
            else
                parts.Add(name);
        }
        string sig = displayName + "(" + string.Join(", ", parts) + ")";
        if (!string.IsNullOrEmpty(fn.ReturnType))
            sig += " -> " + fn.ReturnType;
        return sig;
    }

    private static string ThrowsCell(ThrowsEntry[]? throws)
    {
        if (throws is null || throws.Length == 0) return "—";
        var names = throws.Select(t => "`" + t.ErrorType + "`").Distinct(StringComparer.Ordinal);
        return string.Join(", ", names);
    }

    // ── Appendices ───────────────────────────────────────────────────────────

    private static void EmitAppendices(StringBuilder sb, IReadOnlyList<NamespaceDefinition> namespaces)
    {
        EmitDeprecationAppendix(sb, namespaces);
        EmitCapabilityAppendix(sb, namespaces);
    }

    private static void EmitDeprecationAppendix(StringBuilder sb, IReadOnlyList<NamespaceDefinition> namespaces)
    {
        var rows = new List<(string Qualified, string Replacement, string Kind)>();
        foreach (var ns in namespaces)
        {
            foreach (var fn in ns.Functions)
            {
                if (fn.Deprecation is not null)
                    rows.Add((fn.QualifiedName, fn.Deprecation.ReplacementQualifiedName, "function"));
            }
            foreach (var c in ns.Constants)
            {
                if (c.Deprecation is not null)
                    rows.Add((c.QualifiedName, c.Deprecation.ReplacementQualifiedName, "constant"));
            }
        }
        rows.Sort((a, b) => StringComparer.Ordinal.Compare(a.Qualified, b.Qualified));

        sb.AppendLine("## Appendix A — Deprecated Members");
        sb.AppendLine();
        if (rows.Count == 0)
        {
            sb.AppendLine("_No deprecated members._");
            sb.AppendLine();
            sb.AppendLine("---");
            sb.AppendLine();
            return;
        }
        sb.AppendLine("Each row is reported by static analysis as `SA0830` when used in a script.");
        sb.AppendLine();
        sb.AppendLine("| Member | Kind | Replacement |");
        sb.AppendLine("| ------ | ---- | ----------- |");
        foreach (var (qualified, replacement, kind) in rows)
        {
            sb.Append("| `").Append(qualified).Append("` | ").Append(kind).Append(" | `").Append(replacement).AppendLine("` |");
        }
        sb.AppendLine();
        sb.AppendLine("---");
        sb.AppendLine();
    }

    private static void EmitCapabilityAppendix(StringBuilder sb, IReadOnlyList<NamespaceDefinition> namespaces)
    {
        sb.AppendLine("## Appendix B — Capability-Gated Namespaces");
        sb.AppendLine();
        sb.AppendLine("Embedded hosts can omit capabilities to disable the matching namespaces. A namespace listed");
        sb.AppendLine("here will not appear in the runtime when its capability is not granted.");
        sb.AppendLine();
        sb.AppendLine("| Namespace | Capability |");
        sb.AppendLine("| --------- | ---------- |");
        var gated = namespaces
            .Where(n => !n.IsGlobal && n.RequiredCapability != StashCapabilities.None)
            .OrderBy(n => n.Name, StringComparer.Ordinal);
        foreach (var ns in gated)
        {
            sb.Append("| `").Append(ns.Name).Append("` | `").Append(ns.RequiredCapability).AppendLine("` |");
        }
        sb.AppendLine();
    }

    // ── Helpers ──────────────────────────────────────────────────────────────

    private static string FormatType(string? type) =>
        string.IsNullOrEmpty(type) ? "—" : "`" + type + "`";

    private static string FormatTypeRaw(string type) => "`" + type + "`";

    private static string InlineCodeIfShort(string value)
    {
        if (string.IsNullOrEmpty(value)) return "—";
        return "`" + value + "`";
    }

    private static string EscapeTableCell(string text)
    {
        if (string.IsNullOrEmpty(text)) return "";
        // Pipes break Markdown table rows; everything else is rendered literally.
        return text.Replace("|", "\\|").Replace("\r", "").Replace("\n", " ");
    }

    private static string HeadingAnchor(string heading)
    {
        // GitHub-style: lowercase, strip everything that isn't a-z, 0-9, space,
        // or hyphen, then convert spaces to hyphens. Backticks vanish, em-dashes
        // contribute nothing and the surrounding spaces collapse into the
        // double-hyphen that the existing TOC already uses.
        var sb = new StringBuilder(heading.Length);
        foreach (char ch in heading.ToLowerInvariant())
        {
            if (char.IsLetterOrDigit(ch)) sb.Append(ch);
            else if (ch == ' ') sb.Append('-');
            else if (ch == '-') sb.Append('-');
            // backticks, em-dash (—), parentheses, etc. are dropped
        }
        return sb.ToString();
    }

    private static string Normalize(string text)
    {
        // Force LF endings, strip trailing whitespace on each line, and end the
        // file with exactly one trailing newline.
        var lines = text.Replace("\r\n", "\n").Split('\n');
        var sb = new StringBuilder(text.Length);
        for (int i = 0; i < lines.Length; i++)
        {
            sb.Append(lines[i].TrimEnd());
            if (i < lines.Length - 1) sb.Append('\n');
        }
        string result = sb.ToString();
        // Collapse any run of trailing newlines to one.
        while (result.EndsWith("\n\n", StringComparison.Ordinal))
            result = result.Substring(0, result.Length - 1);
        if (!result.EndsWith("\n", StringComparison.Ordinal))
            result += "\n";
        return result;
    }
}
